version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.20
    depends_on:
      - postgres
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: postgres
            password: postgres
            migrations: true
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=postgres_development_docker,postgres_test_docker
    ports:
      - '54321:5432'
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    # depends_on:
    #   - backend
    ports:
      - '3000:3000'
      - '35729:35729'
      - '9009:9009'
      - '9229:9229'
      - '9230:9230'
    volumes:
      - ./frontend:/opt/app:delegated
      - ./frontend/package.json:/opt/package.json
      - ./frontend/package-lock.json:/opt/package-lock.json
      - /opt/app/node_modules
      - notused:/opt/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  # backend:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./backend
  #   depends_on:
  #     - prisma
  #   ports:
  #     - '4444:4444'
  #   volumes:
  #     - /usr/app/node_modules
  #     - ./backend:/usr/app
  #   environment:
  #     - DEV_DB_HOST=postgres
  #     - DEV_DB_PORT=5432
  #     - DEV_DB_NAME=postgres_development_docker
volumes:
  notused:
