version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.20
    depends_on:
      - postgres
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: postgres
            password: postgres
            migrations: true
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=postgres_development_docker,postgres_test_docker
    ports:
      - '54321:5432'
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'
      - '35729:35729'
      - '9009:9009'
      - '9229:9229'
      - '9230:9230'
    volumes:
      - ./frontend:/opt/app:delegated
      - ./frontend/package.json:/opt/package.json
      - ./frontend/package-lock.json:/opt/package-lock.json
      - /opt/app/node_modules
      - notused:/opt/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - prisma
    ports:
      - '4444:4444'
    volumes:
      - ./backend:/opt/app:delegated
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json
      - /opt/app/node_modules
      - notusedeither:/opt/app/node_modules
    environment:
      - FRONTEND_URL="http://localhost:3000"
      - PRISMA_ENDPOINT="http://localhost:4466/backend/dev"
      - PRISMA_SECRET="prisma_secret"
      - APP_SECRET="app_secret"
      - STRIPE_SECRET="stripe_secret"
      - PORT=4444
volumes:
  notused:
  notusedeither:
